### ISSUE TITLE
[Feature] Command Line Usage

### ISSUE THREAD

**Issue by pidgeon777** [shriprem/Goto-Line-Col-NPP-Plugin#11]
Is there any way to implement some kind of command line?

The idea would be to be able to open a file in Notepad++ by specifying the wanted line and column (byte) position.

**Comment by shriprem** [comment]
@pidgeon777, you may already be aware that Notepad++ has command prompt options that achieve this without using the Goto-Line-Col-NPP plugin.

Just to recap, opening a file with, for example:
`<Your_NPP_Folder_path>\notepad++.exe <Your_Text_File> `**`-n148 -c861`**
will open your text file at line **148** and column **861**.

You can find all command line options for NPP at: https://npp-user-manual.org/docs/command-prompt/

Of course, the NPP command line option for column navigation does not handle TAB and Unicode characters in the more sophisticated manner that Goto-Line-Col-NPP plugin does. Even then, it will still navigate to the correct line and the vicinity of the intended column position. So this should suffice for most text files.

**Comment by pidgeon777** [comment]
Thanks for the prompt reply.

You're right, but I was trying to look for a way to position Notepad++ in a more precise way. Unfortunately, my command-line tool returns column position in bytes, but `Notepad++` accepts column numbers taking the width of any eventual `Tab` character into account.

**Comment by shriprem** [comment]
I have implemented the command line options processing in GotoLineCol. In addition to `-n` and `-c` NPP native options, it supports 8 other options specific to the plugin. For more info, see: [Command Line Options](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/blob/master/docs/CommandLineOptions.md).

Please try the [v2.1.0.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.1.0.0) and let me know if you find any regressions or new issues. Thanks.

### DLL-only manual upgrade of a previously installed version of the plugin
Download the zip file version to match your Notepad++ bitness. Then, either:
1. In Notepad++, navigate to menu: _Settings » Import » Import Plugins..._ and import the dll file extracted from the zip file.
2. OR, Extract the `GotoLineCol.dll` file into the `<NPP_Plugins_folder>/GotoLineCol` folder to overwrite the existing DLL therein.

**Comment by shriprem** [comment]
**Post Script:**
Also, see this Discussions topic: [Why the kludgy syntax for the `-GLCx` options?](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/discussions/14)

**Comment by shriprem** [comment]
Latest Update: [Consolidated GLC Command Line Options](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/blob/master/docs/CommandLineOptions.md) has been introduced in the [v2.1.1.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.1.0.0).

Please ignore my two previous posts on this issue and try the [v2.1.1.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.1.0.0) and let me know if you find any regressions or new issues. Thanks!

**Comment by pidgeon777** [comment]
> Latest Update: [Consolidated GLC Command Line Options](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/blob/master/docs/CommandLineOptions.md) has been introduced in the [v2.1.1.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.1.0.0).
> 
> Please ignore my two previous posts on this issue and try the [v2.1.1.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.1.0.0) and let me know if you find any regressions or new issues. Thanks!

Tried it with this command:

`notepad++ "C:\Work\Test\main.c" -n331 -c7 -z -GLCb1`

Unfortunately, the caret still doesn't get positioned at the proper byte (column) position. In short, it has the same effect as this command, with no GotoLineCol custom switch:

`notepad++ "C:\Work\Test\main.c" -n331 -c7 -z -GLCb1`

Tested with Notepad++ v8.1.5 32bit on Windows 10 x64 Pro.

**Comment by shriprem** [comment]
@pidgeon777, the `-GLC` option should work. I have tested it with x64 & x86 versions, and portable & installed versions of NPP.

Sample command used for byte column positioning (`b` is 1):
**`"E:\Portable\Notepad++ - x86\notepad++.exe" Test_0928.txt -n90 -c632 -z -GLCb1;c1;d1;e18;f1;h1;p1;q1`**
Output:
![image](https://user-images.githubusercontent.com/45252729/135886164-7f37f7d8-37ac-4a1d-9aaa-08e106339cf8.png)

Sample command used for char column column positioning (`b` is 0):
`"E:\Portable\Notepad++ - x86\notepad++.exe" Test_0928.txt -n90 -c632 -z -GLCb1;c1;d1;e18;f1;h1;p1;q1`
Output:
![image](https://user-images.githubusercontent.com/45252729/135885923-3f9b3f30-e607-482e-acc4-5f4ddb1c037d.png)

[_In my NPP, the TAB is set at 3 spaces. Hence a shift of two chars between byte and char column positions._]

If the GLC option is not working for you, check for these:
1. Is the version 2.1.1.0 of the GotoLineCol plugin installed? Check this with the menu option _Plugins » Goto Line, Column » About_.

2. You have not used the `q` sub-option in your command. Either include `q1` sub-option under `GLC`. Or ensure that the GotoLineCol side panel is visible and at the forefront. Even if is is open, but any other NPP panel like Character Panel or Clipboard History or another plugin panel is at the forefront, the GLC panel will count as being invisible and the `GLC` sub-options may not work. Therefore, use the `q1` option as a fail-safe.

I also recommend that you include the `d1;f1;h1` sub-options. You should then see the call tip, the caret flashing in block mode for a second, and the destination character getting highlighted. These visual confirmations will attest that the `GLC` option is working fine.

**Comment by pidgeon777** [comment]
I just did a test with this command:

`notepad++ "C:\Work\test.c" -n87 -c24 -z -GLCb1;c1;d1;e18;f1;h1;p1;q1`

The curious thing is that no call tip appeared, also the plugin itself after the jump reported a position that was coherent with the resulting Notepad++ position, but differed from the wanted byte position:

![image](https://user-images.githubusercontent.com/13739892/135981861-31bfb0a9-80db-4438-ada9-cf38f045f632.png)

I specified byte `24` in my command line, but the plugin reported that it jumped to byte `18`, instead (see the circle mark).

Also, the cursor has been wrongly positioned to the `24th` horizontal char, as if the -b1 option didn't make any effect.

This is confirmed also by the fact that none of the **GLC** options had any effect (no call tip was shown and so on), even if I added them to my command line.

So, the problem unfortunately seems to be still there.

I configured my tab size to 4 spaces.

**Comment by shriprem** [comment]
You haven't confirmed if you have updated the GotoLineColumn DLL. I had this query in my previous post:
1. Is the version 2.1.1.0 of the GotoLineCol plugin installed? Check this with the menu option _Plugins » Goto Line, Column » About._

I reiterate that  I have tested it with single & multiple files; x64 & x86 versions; and portable & installed versions of NPP. So, I strongly suspect that you still have the version of GLC DLL that gets installed with the NPP's Plugins Admin. That would be   GLC v2.0.0.0 which doesn't process any command line options.

If you have updated the GLC DLL, you should see this _GLC » About_ message box:
![image](https://user-images.githubusercontent.com/45252729/136038903-dcddbf3d-bd8b-44bc-a656-d423197693f0.png)

If you are not seeing a matching version number and build timestamp, then use the instructions below to update the DLL.
### DLL-only manual upgrade of a previously installed version of the plugin
Go to the [v2.1.1.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.1.1.0) page. Download the zip file version to match your Notepad++ bitness. Then, either:
1. In Notepad++, navigate to menu: _Settings » Import » Import Plugins..._ and import the dll file extracted from the zip file.
2. OR, Extract the `GotoLineCol.dll` file into the `<NPP_Plugins_folder>/GotoLineCol` folder to overwrite the existing DLL therein.

**Comment by pidgeon777** [comment]
My fault, for some reasons the info you asked for was missing from my post. Here is my **GLC** version:

![image](https://user-images.githubusercontent.com/13739892/136059145-3fb48e26-0265-452f-a568-29a2daf890e3.png)

**Comment by shriprem** [comment]
The plugin is not able to see your command line options. That is why it not processing the byte positioning switch or any of the other visual action switches.

This could happen if an NPP process was already running before you issued the command line options. So, check for these possibilities:

1. If NPP is already running, close it before launching via the command line options.
2. Your NPP may have been configured to minimize to system tray. If so, you should disable this setting. Go to NPP menu: _Settings » Preferences » MISC_. Here, ensure that the _Minimize to system tray_ box is unchecked.

You can also try including the `-multiInst` option in your command line so that NPP always launches in a new process.

The fresh NPP process requirement is not a deficiency of the GLC plugin. Even Microsoft SysInternal's venerable [**Process Explorer**](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) utility is unable to see the command line parameters if you were to issue a fresh set of command line options when an NPP instance is already running or hidden in the system tray.

If you have complied with the two checks listed above and the GLC is still not processing your command line options, please run this extra Process Explorer check before replying back to my post:
1. If you don't already have Process Explorer, download it from the [Microsoft SysInternals page](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer). Note that this tiny utility requires no installation. Just download the zip file, extract the executable to your Desktop, and you can launch it from there.
2. Now, issue the command line options for NPP/GLC after ensuring no prior instance of NPP was running or hidden in systray.
3. Now, in Process Explorer, hover over the NPP entry. Confirm that you are be able to see the options you issued from the command line. Somewhat like this: 
![image](https://user-images.githubusercontent.com/45252729/136068185-80d24b86-2aff-404f-8974-478a0620d2d0.png)

The GLC plugin uses the **[`GetCommandLine`](https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinea)** WINAPI. The command line reported by this API is the command line used to invoke the original NPP process; and will not include a fresh set of command line options used to reinvoke the same NPP process.

**Comment by pidgeon777** [comment]
Thanks for the explanation.

At this point, I suppose my issue is due to the fact that I'm trying to browse my source code by keeping my instance of Notepad++ always active. I didn't know Notepad++ had to be closed every time, before issuing the **GLC** command.

It is a pity because loading a new Notepad++ instance every time have two big disadvantages:
- It could lead to big resources usage and slowness overall (especially with many plugins loaded).
- It would make quick code navigation impossible.

I suppose the only way to fix this, would be to ask Notepad++ developers to hardcode your plugin or part of it in the next Notepad++ release, then.

**Comment by shriprem** [comment]
This feature request has been implemented with this commit: [Implemented -pluginMessage="GLCb1..." command line option for NPP 8.4.2](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/commit/0bc0bc16a2871d5872272a71d4280387dce3a7fe).

This feature is available with the [GotoLineCol 2.4.0.0 Release](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/releases/tag/v2.4.0.0). If you are testing this, please make sure you are using it with the Notepad++ 8.4.2 version. See: [Notepad++ v8.4.2 Release Candidate 2](https://community.notepad-plus-plus.org/topic/23046/notepad-v8-4-2-release-candidate-2).
